zookeeper:
  hosts:
    kafka-zookeeper.westeurope.cloudapp.azure.com:

kafka_broker:
  hosts:
    kafka-broker.westeurope.cloudapp.azure.com:
      broker_id: 0

schema_registry:
  hosts:
    kafka-schema.westeurope.cloudapp.azure.com:

kafka_rest:
  hosts:
    kafka-rest.westeurope.cloudapp.azure.com:

ksql:
  hosts:
    kafka-ksql.westeurope.cloudapp.azure.com:

kafka_connect:
  hosts:
    kafka-connect.westeurope.cloudapp.azure.com:

control_center:
  hosts:
    kafka-control-center.westeurope.cloudapp.azure.com:

all:
  vars:
    ansible_connection: ssh
    ansible_user: kafka-admin
    ansible_become: true
    ansible_ssh_private_key_file: ~/.ssh/terraform_private_key.pem
